name: Publish to NPM

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15"
          cache: "yarn"
      - name: Install package
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Link source code
        run: yarn lint
      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
